# disease_department.py
# Maps each disease your ML model can predict to the closest matching
# department name found in LABAID_Specialized_Hospital_Doctors.csv

DISEASE_TO_DEPARTMENT = {
    "Fungal infection": "Dermatology",
    "Allergy": "Medicine",
    "GERD": "Gastroenterology",
    "Chronic cholestasis": "Hepatology",
    "Drug Reaction": "Medicine",
    "Peptic ulcer disease": "Gastroenterology",
    "AIDS": "Medicine",
    "Diabetes": "Medicine",
    "Gastroenteritis": "Gastroenterology",
    "Bronchial Asthma": "Pulmonology / Medicine",
    "Hypertension": "Cardiology",
    "Migraine": "Neurology",
    "Cervical spondylosis": "Orthopaedic Surgery",
    "Paralysis (brain hemorrhage)": "Neurology",
    "Jaundice": "Hepatology",
    "Malaria": "Medicine",
    "Chicken pox": "Medicine",
    "Dengue": "Medicine",
    "Typhoid": "Medicine",
    "hepatitis A": "Hepatology",
    "Hepatitis B": "Hepatology",
    "Hepatitis C": "Hepatology",
    "Hepatitis D": "Hepatology",
    "Hepatitis E": "Hepatology",
    "Alcoholic hepatitis": "Hepatology",
    "Tuberculosis": "Pulmonology / Medicine",
    "Common Cold": "Medicine",
    "Pneumonia": "Pulmonology / Medicine",
    "Dimorphic hemmorhoids(piles)": "Colorectal Surgery",
    "Heart attack": "Cardiology",
    "Varicose veins": "Vascular Surgery",
    "Hypothyroidism": "Medicine",
    "Hyperthyroidism": "Medicine",
    "Hypoglycemia": "Medicine",
    "Osteoarthristis": "Orthopaedic Surgery",
    "Arthritis": "Pain Medicine & Rheumatology",
    "(vertigo) Paroymsal Positional Vertigo": "ENT",
    "Acne": "Dermatology",
    "Urinary tract infection": "Urology",
    "Psoriasis": "Dermatology",
    "Impetigo": "Dermatology",
}
